<?php $dados = $this->dadospagina;?>

<div id="content">
	<div class="content-wrapper">		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="im-user"></i> <strong>CADASTRO DE FUNCIONÁRIO</strong></h1>
                
                <ul id="crumb" class="breadcrumb">
                </ul>
                <!-- End .breadcrumb -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/funcionario/funcionario/listagem')?>">
								<button class="btn btn-primary" type="button"><i class="fa-eye-open"></i> VISUALIZAR CADASTROS</button>
							</a>
                        </div>
                        
                    </div>
                </div>
                <!-- End .option-buttons -->
            </div>
		</div>
		<form id="formCadastro" class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/usuario/usuario/index')?>">
			<input type="hidden" id="imagem" name="imagem" value="">
			<input type="hidden" id="id_foto" name="id_foto" value="<?php echo $dados['geral']['sn_foto']?>">
			<input type="hidden" id="usuario" name="usuario" value="<?php echo $dados['geral']['id_usuario']?>">
			<div class="row">
				<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12" id="wrapper_booth" style="display: none;">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h4 class="panel-title" style="text-align: center;">									
								<span>Compartilhe o dispositivo, clique no crop (Quadrado pontilhado)::: para limitar o tamanho da foto, enquadre com o rosto do cliente e clique na câmera para tirar a foto</span>
							</h4>
						</div>
						<div class="panel-body">
							<div id="wrapper">
            					<div id="example"></div>       
                    		</div>
						</div>
					</div>
				</div>
				
				<div class="col-lg-3 col-md-3 col-sm-3">
					<div class="panel panel-default plain">
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<div class="col-lg-12 col-md-12" align="center">
								    <?php $imagem = empty($dados['geral']['sn_foto']) ?'/assets/img/user.png' : '/img/fotos/usuario/'.$dados['geral']['id_usuario'].'.png';?>
									<img id="foto" name="foto" alt="" style="cursor: pointer;" src="<?php echo $this->baseUrl($imagem)?>">
								</div>
							</div>
						</div>
					</div>
				</div>
			
				<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
					<div class="panel panel-default plain">
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Registro: </label>
								<div class="col-lg-3 col-md-3">
									<input class="form-control" type="text" id="id_funcionario" name="id_funcionario" readonly="readonly" value="<?php echo $this->dadospagina['id_funcionario']?>" />
								</div>
								
								<div class="col-lg-2 col-md-2">
									<label class="checkbox-inline">
										<input type="checkbox" value="1" <?php if($this->dadospagina['id_ativo']==1){ echo 'checked ="checked"';}?> style="position: absolute; opacity: 0;" id="id_ativo" name="id_ativo"  /><b>ATIVO</b>
									</label>
								</div>                								
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Nome<b style="color: red;">*</b>:</label>
								<div class="col-lg-6 col-md-6">
									<input type="text" class="form-control" id="st_nome" name="st_nome" required  value="<?php echo $this->dadospagina['st_nome']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Sexo<b style="color: red;">*</b>:</label> 
								<div class="col-lg-4 col-md-4">
									<label class="radio-inline"> <input type="radio" name="st_sexo" value="M" <?php if($this->dadospagina['st_sexo'] == "M")  echo "checked"?> required >Masculino</label> 
									<label class="radio-inline"> <input type="radio" name="st_sexo" value="F" <?php if($this->dadospagina['st_sexo'] == "F")  echo "checked"?> required >Feminino</label>
								</div>
							</div>
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Telefone<b style="color: red;">*</b>:</label>
								<div class="col-lg-3 col-md-3">
									<input type="text" class="form-control" id="st_fonecontato" name="st_fonecontato" required value="<?php echo $this->dadospagina['st_fonecontato']?>" />
								</div>
								<label class="col-lg-2 col-md-2 col-sm-12 control-label">Data de Nascimento:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="dt_nascimento" name="dt_nascimento" value="<?php echo $this->dadospagina['dt_nascimento']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Email:</label>
								<div class="col-lg-3 col-md-3">
									<input type="text" class="form-control" id="st_email" name="st_email" value="<?php echo $this->dadospagina['st_email']?>" />
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">CPF:</label>
								<div class="col-lg-3 col-md-3">
									<input type="text" class="form-control" id="st_cpf" name="st_cpf" value="<?php echo $this->dadospagina['st_cpf']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">RG</label>
								<div class="col-lg-3 col-md-3">
									<input type="text" class="form-control" id="st_rg" name="st_rg" maxlength="10" value="<?php echo $dados['geral']['nr_rg']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">CARGO</label>
								<div class="col-lg-3 col-md-3">
									<select id="st_tipo_logradouro" class="form-control select2" autofocus="autofocus" required name="st_tipo_logradouro">
										<option>GERENTE</option>
										<?php foreach ($this->cargo as $value):?>
											<option value="<?php echo $value['id_cargo']?>" <?php if($this->dadospagina['id_cargo'] == $value['id_cargo']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default plain">
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">CTPS </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_ctps" name="st_ctps" value="<?php echo $this->dadospagina['st_ctps']?>" />
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">SÉRIE </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_serie" name="st_serie" value="<?php echo $this->dadospagina['st_serie']?>" />
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">ADMISSÃO </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_serie" name="st_serie" value="<?php echo $this->dadospagina['st_serie']?>" />
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">VL SALÁRIO </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_serie" name="st_serie" value="<?php echo $this->dadospagina['st_serie']?>" />
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">BANCO </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_ctps" name="st_ctps" value="<?php echo $this->dadospagina['st_ctps']?>" />
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">AGÊNCIA </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_serie" name="st_serie" value="<?php echo $this->dadospagina['st_serie']?>" />
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">CONTA </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_serie" name="st_serie" value="<?php echo $this->dadospagina['st_serie']?>" />
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">TIPO CONTA </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_serie" name="st_serie" value="<?php echo $this->dadospagina['st_serie']?>" />
								</div>
							</div>
						
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">CEP </label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_cep" name="st_cep" value="<?php echo $this->dadospagina['st_cep']?>" />
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Tipo </label>
								<div class="col-lg-2 col-md-2">
									<select id="st_tipo_logradouro" class="form-control select2" autofocus="autofocus" required name="st_tipo_logradouro">
										<option></option>
										<?php foreach ($this->TipoLogradouro as $value):?>
											<option value="<?php echo $value['id_tipo_logradouro']?>" <?php if($this->dadospagina['st_tipo_logradouro'] == $value['id_tipo_logradouro']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Logradouro</label>
								<div class="col-lg-5 col-md-5">
									<input type="text" class="form-control" id="st_logradouro" name="st_logradouro" value="<?php echo $this->dadospagina['st_logradouro']?>">
								</div>
								
							</div>
						
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Complemento</label>
								<div class="col-lg-6 col-md-6">
									<input type="text" class="form-control" id="st_complemento" name="st_complemento" value="<?php echo $this->dadospagina['st_complemento']?>">
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Nº</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_numero" name="st_numero" value="<?php echo $this->dadospagina['st_numero']?>">
								</div>
							</div>
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Bairro</label>
								<div class="col-lg-4 col-md-4">
									<input type="text" class="form-control" id="st_bairro" name="st_bairro" value="<?php echo $this->dadospagina['st_bairro']?>">
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Cidade</label>
								<div class="col-lg-4 col-md-4">
									<input type="text" class="form-control" id="st_cidade" name="st_cidade" value="<?php echo $this->dadospagina['st_cidade']?>">
								</div>
								
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">UF</label>
								<div class="col-lg-1 col-md-2">
									<input type="text" class="form-control" id="st_estado" name="st_estado" value="<?php echo $this->dadospagina['st_estado']?>">
								</div>
							</div>							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Observações:</label>
								<div class="col-lg-10 col-md-10">
									<textarea class="form-control" rows="2" id="ds_observacao" name="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
								</div>
							</div>										
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default toggle">
        				<button class="btn btn-success  ml15" type="submit"><i class="fa-ok"></i> Cadastrar</button>
        				<a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/cliente/cliente/')?>">
        					<button class="btn btn-primary" type="button"><i class="fa-plus-sign"></i> Cadastrar Novo</button>
        				</a>
        			</div>	
				</div>
			</div>
		</form>
	</div>
	<div class="clearfix"></div>
</div>

<!-- ModalCPFIguais -->
<div class="modal fade" id="modalCPF">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Existe(m) esse(s) Registro(s) para esse CPF</h4>
            </div>
              <div class="modal-body">
                <div class="row">
					<div id="RegCpf"></div>       
        		</div>            
            </div>
            <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Continuar Cadastro</button>
          </div>
        </div>
    </div>
</div>
<!-- Fim Modal CPF iguais--> 

<!-- Modal valida CPF -->
<div class="modal" id="modalVal">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Alerta</h4>
            </div>
              <div class="modal-body">
                <div class="row">
					<div>O CPF digitado não é valido</div>       
        		</div>            
            </div>
            <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          	</div>
        </div>
    </div>
</div>
<!-- Fim Modal valida CPF--> 


<?php if(!empty($this->msg)):?>
	<?php if($this->msg == 2) :?>
		<div class="alert alert-success fade in">
			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
			<i class="fa-ok alert-icon s24"></i>
			<strong>Registro gravado com sucesso!</strong>
		</div>
	<?php else :?>
		<div class="alert alert-danger fade in">
			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
			<strong>Ocorreu um erro ao gravar!</strong>
		</div>
	<?php endif;?>
<?php endif;?>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/photobooth_min.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/script.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/hijs.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/usuario/usuario.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/plugins/function.js')?>"> </script>
<link href="<?php echo $this->baseUrl('/js/photobooth/page.css')?>" rel="stylesheet" />

<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/maxlength/bootstrap-maxlength.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/bootstrap-filestyle/bootstrap-filestyle.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/maskedinput/jquery.maskedinput.js"></script>

<script type="text/javascript">

function mascara(o,f){
    v_obj=o;
    v_fun=f;
    setTimeout("execmascara()",1);
}
function execmascara(){
    v_obj.value=v_fun(v_obj.value);
}
function mtel(v){
    v=v.replace(/\D/g,"");
    v=v.replace(/^(\d{2})(\d)/g,"($1) $2");
    v=v.replace(/(\d)(\d{4})$/,"$1-$2");
    return v;
}
function data(v){
	v=v.replace(/\D/g,"");
    v=v.replace(/(\d{2})(\d)/,"$1/$2");
    v=v.replace(/(\d{2})(\d)/,"$1/$2");    
    return v;
}
function id( el ){
	return document.getElementById( el );
}
window.onload = function(){
	id('st_fonecontato').onkeypress = function(){
		mascara( this, mtel );
	},
	id('st_fonecelular').onkeypress = function(){
		mascara( this, mtel );
	},
	id('dt_nascimento').onkeypress = function(){
		mascara( this, data );
	}
}
</script>