<div id="content">
	<div class="content-wrapper">		
		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="im-user"></i> <strong>LISTAGEM DE FUNCIONÁRIOS</strong></h1>
                <ul id="crumb" class="breadcrumb">
                </ul>
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/funcionario/funcionario/')?>">
								<button class="btn btn-primary" type="button"><i class="st-file-add"></i> ADICIONAR FUNCIONÁRIOS</button>
							</a>
                        </div>
                    </div>
                </div>
            </div>
		</div>
		
		<?php if(!empty($this->rsFuncionario) ):?>
		
			<div class="panel panel-default plain toggle panelClose panelRefresh">
                                <!-- Start .panel -->
                <div class="panel-heading">
                    <h4 class="panel-title">Relatório de Cadastros</h4>
                </div>
                <div class="panel-body">
                	<table id="table-object" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>Registro</th>
								<th>Nome</th>
								<th>Nascido em</th>
								<th>Sexo</th>
								<th>E-mail</th>
								<th>Status</th>
								<th>Ação</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->rsFuncionario as $rsFuncionario) : ?>
								<tr>
                                	<td>
										<?php echo str_pad($rsFuncionario['id_funcionario'], 5, "0", STR_PAD_LEFT); ?>
									</td>
                                    <td>
                                        <?php echo $rsFuncionario['st_nome'] ?>
                                    </td>
                                    <td>
                                        <?php
                                        	if(!empty($rsFuncionario["dt_nascimento"])){
                                                list($YY,$mm,$dd) = explode('-',$rsFuncionario["dt_nascimento"]);
                                                echo $dd.'/'.$mm.'/'.$YY; 
                                        	}
                                        ?>
                                    </td>
                                    <td><?php echo $rsFuncionario['st_sexo'] == 'M' ? 'Masculino' : 'Feminino' ?></td>
                                    <td><?php echo $rsFuncionario['st_email'] ?></td>
                                    <td><?php echo $rsFuncionario['id_ativo'] == 1 ? 'ATIVO':'INATIVO';?></td>
                                    <td style="text-align: center;">
										<a href="<?php echo $this->baseUrl('/funcionario/funcionario/index/id/'.base64_encode($rsFuncionario["dt_nascimento"].'@'.$rsFuncionario['id_funcionario']))?>"><span class="fa-edit s20" title="Editar Registro"></span></a> | 
										<a href="<?php echo $this->baseUrl('/funcionario/funcionario/inativarregistro/id/'.base64_encode($rsFuncionario["dt_nascimento"].'@'.$rsFuncionario['id_funcionario']))?>"><span class="fa-remove s20" title="Inativar Registro"></span></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
						</tbody>
					</table>
                </div>
    		</div>
		<?php else :?>
            <div class="alert alert-danger fade in" style="text-align: center;">
                <strong>NÃO EXISTEM FUNCIONÁRIOS CADASTRADOS, CLIQUE NO BOTÃO "ADICIONAR FUNCIONÁRIO" PARA REALIZAR OS CADASTROS</strong>
            </div>
		<?php endif;?>
	</div>
	<div class="clearfix"></div>
</div>