<?php $dados = $this->dadospagina;?>

<div id="content">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="ec-pencil2"></i><strong>CADASTRO DE USUÁRIOS</strong></h1>
                
                <ul id="crumb" class="breadcrumb">
                </ul>
                <!-- End .breadcrumb -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/usuario/usuario/listagem')?>">
								<button class="btn btn-primary" type="button">VISUALIZAR CADASTRADOS</button>
							</a>
                        </div>
                        
                    </div>
                </div>
            </div>
		</div>
		
		<form id="formCadastro" class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/usuario/usuario/index')?>">
			<input type="hidden" id="imagem" name="imagem" value="">
			<input type="hidden" id="id_foto" name="id_foto" value="<?php echo $dados['geral']['sn_foto']?>">
			<input type="hidden" id="usuario" name="usuario" value="<?php echo $dados['geral']['id_usuario']?>">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain">
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">FUNCIONÁRIO<b style="color: red;"> *</b></label>
								<div class="col-lg-8 col-md-8">
									
									<select id="nm_usuario" class="form-control select2" required name="nm_usuario">
										<option></option>
										<?php foreach ($this->rsFuncionario as $value):?>
											<option value="<?php echo $value['id_funcionario']?>"><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								
								</div>
								<div class="col-lg-2 col-md-2">
									<label class="checkbox-inline">
										<input type="checkbox" value="1" <?php if($dados['geral']['id_ativo']==1){ echo 'checked ="checked"';}?> style="position: absolute; opacity: 0;" id="id_ativo" name="id_ativo"  />ATIVO
									</label>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">LOGIN<b style="color: red;"> *</b></label>
								<div class="col-lg-8 col-md-8">
									<input class="form-control" type="text" id="st_usuario" name="st_usuario" placeholder=" " maxlength="40" required value="<?php echo $dados['geral']['st_usuario']?>" />
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">PERFIL<b style="color: red;"> *</b></label>
								<div class="col-lg-4 col-md-4">
									<select id="id_perfil" class="form-control select2" required name="id_perfil">
										<option></option>
										<?php foreach ($this->perfil as $value):?>
											<option value="<?php echo $value['id_perfil']?>"><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>							
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default toggle">
        				<button class="btn btn-success  ml15" type="submit"><i class="fa-ok"></i> Cadastrar</button>
        				<button class="btn btn-danger  ml15" type="submit"><i class="fa-remove"></i> Cancelar</button>
        			</div>	
				</div>
			</div>
		</form>
	</div>
	<div class="clearfix"></div>
</div>

<!-- ModalCPFIguais -->
<div class="modal fade" id="modalCPF">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Existe(m) esse(s) Registro(s) para esse CPF</h4>
            </div>
              <div class="modal-body">
                <div class="row">
					<div id="RegCpf"></div>       
        		</div>            
            </div>
            <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Continuar Cadastro</button>
          </div>
        </div>
    </div>
</div>
<!-- Fim Modal CPF iguais--> 

<!-- Modal valida CPF -->
<div class="modal" id="modalVal">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Alerta</h4>
            </div>
              <div class="modal-body">
                <div class="row">
					<div>O CPF digitado não é valido</div>       
        		</div>            
            </div>
            <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          	</div>
        </div>
    </div>
</div>
<!-- Fim Modal valida CPF--> 


<?php if(!empty($this->msg)):?>
	<?php if($this->msg == 2) :?>
		<div class="alert alert-success fade in">
			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
			<i class="fa-ok alert-icon s24"></i>
			<strong>Registro gravado com sucesso!</strong>
		</div>
	<?php else :?>
		<div class="alert alert-danger fade in">
			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
			<strong>Ocorreu um erro ao gravar!</strong>
		</div>
	<?php endif;?>
<?php endif;?>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/photobooth_min.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/script.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/hijs.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/usuario/usuario.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/plugins/function.js')?>"> </script>
<link href="<?php echo $this->baseUrl('/js/photobooth/page.css')?>" rel="stylesheet" />

<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/maxlength/bootstrap-maxlength.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/bootstrap-filestyle/bootstrap-filestyle.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/maskedinput/jquery.maskedinput.js"></script>

<script type="text/javascript">

function mascara(o,f){
    v_obj=o;
    v_fun=f;
    setTimeout("execmascara()",1);
}
function execmascara(){
    v_obj.value=v_fun(v_obj.value);
}
function mtel(v){
    v=v.replace(/\D/g,"");
    v=v.replace(/^(\d{2})(\d)/g,"($1) $2");
    v=v.replace(/(\d)(\d{4})$/,"$1-$2");
    return v;
}
function data(v){
	v=v.replace(/\D/g,"");
    v=v.replace(/(\d{2})(\d)/,"$1/$2");
    v=v.replace(/(\d{2})(\d)/,"$1/$2");    
    return v;
}
function id( el ){
	return document.getElementById( el );
}
window.onload = function(){
	id('st_fonecontato').onkeypress = function(){
		mascara( this, mtel );
	},
	id('st_fonecelular').onkeypress = function(){
		mascara( this, mtel );
	},
	id('dt_nascimento').onkeypress = function(){
		mascara( this, data );
	}
}
</script>