<?php $dados = $this->dadospagina;?>

<div id="content">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="fa-barcode"></i><strong>CADASTRO DE PRODUTOS</strong></h1>
                
                <ul id="crumb" class="breadcrumb">
                </ul>
                <!-- End .breadcrumb -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/produto/produto/listagem')?>">
								<button class="btn btn-primary" type="button">LISTAR DE PRODUTOS</button>
							</a>
                        </div>
                        
                    </div>
                </div> 
            </div>
		</div>
		<?php if(!empty($this->msg)):?>
        	<?php if($this->msg == 2) :?>
        		<div class="alert alert-success fade in">
        			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
        			<i class="fa-ok alert-icon s24"></i>
        			<strong>Registro gravado com sucesso!</strong>
        		</div>
        	<?php else :?>
        		<div class="alert alert-danger fade in">
        			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
        			<strong>Ocorreu um erro ao gravar!</strong>
        		</div>
        	<?php endif;?>
        <?php endif;?>	
        
      	<form id="formCadastro" class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/produto/produto/index')?>">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain">
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Registro: </label>
								<div class="col-lg-3 col-md-3">
									<input class="form-control" type="text" id="id_produto" name="id_fornecedor" readonly="readonly" value="<?php echo $this->dadospagina['id_produto']?>" />
								</div>
							</div>						
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Nome <b style="color: red;"> *</b></label>
								<div class="col-lg-5 col-md-5">
									<input type="text" class="form-control" id="st_nome" name="st_nome" required  value="<?php echo $this->dadospagina['st_nome']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Categoria<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
									<select id="id_grupo_produto" class="form-control select2" name="id_grupo_produto" required>
                                    	<option></option>
										<?php foreach ($this->grupoProduto as $value):?>
											<option value="<?php echo $value['id_grupo_produto']?>" <?php if($this->dadospagina['id_grupo_produto'] == $value['id_grupo_produto']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Unidade <b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
									<select id="id_unimed" class="form-control select2" name="id_unimed" required>
										<option></option>
										<?php foreach ($this->unimed as $value):?>
											<option value="<?php echo $value['id_unimed']?>" <?php if($this->dadospagina['id_unimed'] == $value['id_unimed']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							
							<div class="form-group">
                                <label class="col-lg-1 control-label">Marca <b style="color: red;">*</b></label>
                                <div class="col-lg-2">
                                    <select id="id_marca_produto" class="form-control select2" name="id_marca_produto" required >
										<option></option>
										<?php foreach ($this->marcaProduto as $value):?>
											<option value="<?php echo $value['id_marca_produto']?>" <?php if($this->dadospagina['id_marca_produto'] == $value['id_marca_produto']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
                                </div>
                                
                                <label class="col-lg-1 control-label">Modelo </label>
                                <div class="col-lg-2">
                                   <input class="form-control" name="st_modelo" id="st_modelo" type="text" value="<?php echo $this->dadospagina['st_modelo']?>">												
                                </div>
                                
                                <label class="col-lg-1 control-label">lote </label>
                                <div class="col-lg-2">
                                    <input class="form-control" name="st_lote" id="st_lote" type="text" value="<?php echo $this->dadospagina['st_lote']?>">
                                </div>
                                
                                <label class="col-lg-1 control-label">Validade <b style="color: red;">*</b></label>
                                <div class="col-lg-2">
                                    <input class="form-control" type="text" name="dt_validade" id="dt_validade" value="<?php echo $this->dadospagina['dt_validade']?>">
                                </div>
                            </div>
							<div class="form-group">
								<label class="col-lg-1 control-label">Estoque Inicial </label>
                                <div class="col-lg-2">
                                    <input class="form-control" name="qt_entrada" id="qt_entrada" type="text" value="<?php echo $this->dadospagina['qt_entrada']?>">
                                </div>
                                <label class="col-lg-1 control-label">Estoque Minímo <b style="color: red;">*</b></label>
                                <div class="col-lg-2">
                                    <input class="form-control" name="qt_estoque_minimo" id="qt_estoque_minimo" type="text" required value="<?php echo $this->dadospagina['qt_estoque_minimo']?>">
                                </div>
                                <label class="col-lg-1 control-label">Localização <b style="color: red;">*</b></label>
                                <div class="col-lg-2">
                                    <input class="form-control" name="st_localizacao" id="st_localizacao" type="text" value="<?php echo $this->dadospagina['st_localizacao']?>">
                                </div>
                                <label class="col-lg-1 control-label">Estoque Atual</label>
                                <div class="col-lg-2">
                                    <input class="form-control" name="qt_saldo" id="qt_saldo" type="text" value="<?php echo $this->dadospagina['qt_saldo']?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-1 control-label">Fornecedor <b style="color: red;">*</b></label>
                                <div class="col-lg-11">
                                    <select name="id_fornecedor[]" id="id_fornecedor[]" class="form-control select2" multiple required>
                                    	<option></option>
                                        <?php foreach ($this->fornecedor as $value):?>
											<option value="<?php echo $value['id_fornecedor']?>" <?php if($this->dadospagina['id_fornecedor'] == $value['id_fornecedor']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
                                    </select>
                                </div>
                            </div>
														
							<div class="form-group">
                                <label class="col-lg-2 control-label">Valor de Compra</label>
                                <div class="col-lg-4">
                                    <input class="form-control" name="num_valor_custo" id="num_valor_custo" type="text"  value="<?php echo $this->dadospagina['num_valor_custo']?>">
                                </div>

                                <label class="col-lg-2 control-label">Valor de Venda</label>
                                <div class="col-lg-4">
                                    <input class="form-control" name="num_valor_venda" id="num_valor_venda" type="text"  value="<?php echo $this->dadospagina['num_valor_venda']?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Despesas com Acessórios</label>
                                <div class="col-lg-4">
                                    <input class="form-control" name="num_desp_acessorio" id="num_desp_acessorio" type="text" value="<?php echo empty($this->dadospagina['num_desp_acessorio']) ? '0,00':$this->dadospagina['num_desp_acessorio']?>">
                                </div>
                                <label class="col-lg-2 control-label">Lucro Utilizado (%)</label>
                                <div class="col-lg-4">
                                    <input class="form-control" name="st_lucro" id="st_lucro" type="text" value="<?php echo $this->dadospagina['st_lucro']?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Outros Custos</label>
                                <div class="col-lg-4">
                                    <input class="form-control" name="num_outro_custo" id="num_outro_custo" type="text" value="<?php echo empty($this->dadospagina['num_outro_custo']) ? '0,00':$this->dadospagina['num_outro_custo']?>">
                                </div>
                                <label class="col-lg-2 control-label">Comissão (%)</label>
                                <div class="col-lg-4">
                                    <input class="form-control" name="st_comissao" id="st_comissao" type="text" value="<?php echo $this->dadospagina['st_comissao']?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Custos Final</label>
                                <div class="col-lg-4">
                                    <input class="form-control" name="num_custo_final" id="num_custo_final" type="text" value="<?php echo $this->dadospagina['num_custo_final']?>">
                                </div>
                            </div>
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default toggle">
        				<button class="btn btn-success  ml15" type="submit"><i class="fa-ok"></i> Cadastrar</button>
        				<a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/produto/produto/')?>">
        					<button class="btn btn-primary" type="button"><i class="fa-plus-sign"></i> Cadastrar Novo</button>
        				</a>
        			</div>	
				</div>
			</div>
        </form>
	</div>
</div>
<div class="clearfix"></div>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/produto/produto.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/mascara.js')?>"> </script>