<div id="content">
	<div class="content-wrapper">		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="fa fa-barcode"></i> <strong>LISTAGEM DE PRODUTOS</strong></h1>
				<ul id="crumb" class="breadcrumb">
                </ul>
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                    	<div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/produto/produto/')?>">
								<button class="btn btn-primary" type="button"><i class="st-file-add"></i> ADICIONAR PRODUTO</button>
							</a>
                        </div>
					</div>
				</div>
			</div>
		</div>
		<?php if(!empty($this->rsProduto)):?>
			<div class="outlet">
    			<form class="form-horizontal group-border hover-stripped" role="form">
					<div class="row">
    					<div class="col-lg-12">
							<div class="panel panel-default plain toggle panelClose panelRefresh">
								<div class="panel-body">
									<table id="responsive-datatables" class="table table-bordered table-striped table-hover dt-responsive non-responsive" >
										<thead>
											<tr>
												<th>Registro</th>
												<th>Nome</th>
												<th>Marca</th>
												<th>Categoria</th>
												<th>Unidade de Medida</th>
												<th>Ação</th>
											</tr>
										</thead>
										<tbody>
											<?php foreach ($this->rsProduto as $rProduto) : ?>
												<tr>
                                                	<td><?php echo str_pad($rProduto['id_produto'], 5, "0", STR_PAD_LEFT); ?></td>
                                                    <td><?php echo $rProduto['st_nome'] ?></td>
                                                    <td><?php echo $rProduto['nm_marca'] ?></td>
                                                    <td><?php echo $rProduto['nm_categoria'] ?></td>
                                                    <td><?php echo $rProduto['nm_unimed'] ?></td>
                                                    <td style="text-align: center;">
                										<a href="<?php echo $this->baseUrl('/produto/produto/index/id/'.base64_encode($rProduto["dt_cadastro_prod"].'@'.$rProduto['id_produto']))?>"><span class="fa-edit s20" title="Editar Registro"></span></a> 
                									</td>
                                                </tr>
                                            <?php endforeach; ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
    				</div>
    			</form>
    		</div>
		<?php else :?>
            <div class="alert alert-danger fade in" style="text-align: center;">
                <strong>NÃO EXISTEM PRODUTOS CADASTRADOS, CLIQUE NO BOTÃO "ADICIONAR PRODUTO" PARA REALIZAR OS CADASTROS</strong>
            </div>
		<?php endif;?>
	</div>
	<div class="clearfix"></div>
</div>