<div id="header">
    <div class="container-fluid">
        <div class="navbar">
            <div class="navbar-header" style="align:center">
                <a class="navbar-brand" href="<?php echo $this->baseUrl()?>/administrativo/painel">
                    <img width="85%" src="">
                    <strong>AUTOSYS</strong><br/>Sistema de Oficina
                </a>
            </div>
            <nav class="top-nav" role="navigation">
                <ul class="nav navbar-nav pull-left">
                    <li id="toggle-sidebar-li">
                        <a href="#" id="toggle-sidebar"><i class="en-arrow-left2"></i></a>
                    </li>
                    
                    <li class="dropdown">
                        <a href="<?php echo $this->baseUrl('index/mudar-cenario'); ?>">
                            <i class="ec-download"></i>
                            <strong><?php echo strtoupper(Zend_Auth::getInstance()->getIdentity()->organizacao->st_nome_fantasia) ?></strong>
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown">
                            <img class="user-avatar" src="<?php echo $this->baseUrl()?>/img/fotos/usuario/<?php echo App_Identity::getIdUsuario()?>.png"><?php echo App_Identity::get('st_usuario'); ?>
                        </a>
                        <ul class="dropdown-menu right" role="menu">
                            <li><a href="profile.html"><i class="st-user"></i> Profile</a></li>
                            <li><a href="#"><i class="st-settings"></i> Configurações</a></li>
                            <li><a href="<?php echo $this->baseUrl('auth')?>"><i class="im-exit"></i> Sair</a></li>
                        </ul>
                    </li>
                    <!-- <li id="toggle-right-sidebar-li"><a href="#" id="toggle-right-sidebar"><i class="ec-users"></i> <span class="notification">3</span></a></li>-->
                </ul>
            </nav>
        </div>
    </div>
    <!-- Start .header-inner -->
</div>

<!-- Start #sidebar -->

<div id="sidebar">
    <!-- Start .sidebar-inner -->
    <div class="sidebar-inner">
        <!-- Start .sidebar-panel -->
        <div class="sidebar-panel panel-nav-header dark-bg">
            <h4 class="sidebar-panel-title">Expandir Menu</h4>
            <a href="#" id="expand-all-submenus" class="expand-submenus tip" title="Expand all sub menus"><i class="en-plus"></i> </a>
        </div>
        <!-- End .sidebar-panel -->
        <!-- Start #sideNav -->
        <ul id="sideNav" class="nav nav-pills nav-stacked">
            <li class="top-search">
                <form>
                    <input type="text" name="search" placeholder="Pesquisar ...">
                    <button type="submit"><i class="ec-search s20"></i>
                    </button>
                </form>
            </li>
            
            <?php 
                $mMenu = new Model_Sistema_Menu();
                $select = $mMenu->select();
                $select->order('num_ordem');
                $rsMenu = $mMenu->fetchAll($select)->toArray(); 
                
                $mSubmenu = new Model_Sistema_Submenu();
                $select = $mSubmenu->select();
                $select->order('num_ordem');
                $rsSubmenu = $mSubmenu->fetchAll($select)->toArray();
            ?>
                
            <?php $x=0;?> 
            <?php foreach($rsMenu as $menu) : ?>
            
                <li>
                    <a href="<?php echo $this->baseUrl($menu['st_href'])?>"><?php echo $menu["st_nome"] ?><i class="<?php echo $menu['st_classe_ui'] ?>"></i></a>

					<?php if($rsSubmenu[$x]['id_menu'] == $menu['id_menu']) : ?>
					<?php $x+=1;?>
                        <ul class="nav sub">
                            <?php foreach($rsSubmenu as $submenu) : ?>
                            	<?php if($menu['id_menu'] == $submenu['id_menu']) :?>
                            		<li><a href="<?php echo $this->baseUrl($submenu['st_href'])?>"><i class="en-arrow-right7"></i><?php echo $submenu["st_nome"] ?></a></li>
                            	<?php endif;?>                            
                            <?php endforeach; ?>
                        </ul>
                    <?php endif;?> 
                    
                </li>
                 
            <?php endforeach; ?>
            
        </ul>
    </div>
    <!-- End .sidebar-inner -->
</div>

<!-- End #sidebar -->

<!-- Start #right-sidebar -->
<div id="right-sidebar" class="hide-sidebar">
    <!-- Start .sidebar-inner -->
    <div class="sidebar-inner">
        <div class="sidebar-panel mt0">
            <div class="sidebar-panel-content fullwidth pt0">
                <div class="chat-user-list">
                    <form class="form-horizontal chat-search" role="form">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search for user...">
                            <button type="submit"><i class="ec-search s16"></i>
                            </button>
                        </div>
                        <!-- End .form-group  -->
                    </form>
                    <ul class="chat-ui bsAccordion">
                        <li>
                            <a href="#">Favorites <span class="notification teal">4</span><i class="en-arrow-down5"></i></a>
                            <ul class="in">
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">Chad Engle
                                        <span class="has-message"><i class="im-pencil"></i></span>
                                    </a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/54.jpg" alt="@alagoon">Anthony Lagoon</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/52.jpg" alt="@koridhandy">Kory Handy</a>
                                    <span class="status"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/50.jpg" alt="@divya">Divia Manyan</a>
                                    <span class="status"><i class="en-dot"></i></span>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Online <span class="notification green">3</span><i class="en-arrow-down5"></i></a>
                            <ul class="in">
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/51.jpg" alt="@kolage">Eric Hofman</a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/55.jpg" alt="@mikebeecham">Mike Beecham</a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/53.jpg" alt="@derekebradley">Darek Bradly</a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Offline <span class="notification red">5</span><i class="en-arrow-down5"></i></a>
                            <ul>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/56.jpg" alt="@laurengray">Lauren Grey</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">Chad Engle</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/58.jpg" alt="@frankiefreesbie">Frankie Freesibie</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/57.jpg" alt="@joannefournier">Joane Fornier</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/59.jpg" alt="@aiiaiiaii">Alia Alien</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="chat-box">
                    <h5>Chad Engle</h5>
                    <a id="close-user-chat" href="#" class="btn btn-xs btn-primary"><i class="en-arrow-left4"></i></a>
                    <ul class="chat-ui chat-messages">
                        <li class="chat-user">
                            <p class="avatar">
                                <img src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">
                            </p>
                            <p class="chat-name">Chad Engle <span class="chat-time">15 seconds ago</span>
                            </p>
                            <span class="status online"><i class="en-dot"></i></span>
                            <p class="chat-txt">Hello Sugge check out the last order.</p>
                        </li>
                        <li class="chat-me">
                            <p class="avatar">
                                <img src="<?php echo $this->baseUrl()?>/assets/img/avatars/48.jpg" alt="A">
                            </p>
                            <p class="chat-name">Admin <span class="chat-time">10 seconds ago</span>
                            </p>
                            <span class="status online"><i class="en-dot"></i></span>
                            <p class="chat-txt">Ok i will check it out.</p>
                        </li>
                        <li class="chat-user">
                            <p class="avatar">
                                <img src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">
                            </p>
                            <p class="chat-name">Chad Engle <span class="chat-time">now</span>
                            </p>
                            <span class="status online"><i class="en-dot"></i></span>
                            <p class="chat-txt">Thank you, have a nice day</p>
                        </li>
                    </ul>
                    <div class="chat-write">
                        <form action="#" class="form-horizontal" role="form">
                            <div class="form-group">
                                <textarea name="sendmsg" id="sendMsg" class="form-control elastic" rows="1"></textarea>
                                <a role="button" class="btn" id="attach_photo_btn">
                                    <i class="fa-picture s20"></i>
                                </a>
                                <input type="file" name="attach_photo" id="attach_photo">
                            </div>
                            <!-- End .form-group  -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End .sidebar-inner -->
</div>
<!-- End #right-sidebar -->