<div id="header">
    <div class="container-fluid">
        <div class="navbar">
            <div class="navbar-header" style="align:center">
                <a class="navbar-brand" href="<?php echo $this->baseUrl()?>/administrativo/painel">
                    <img width="85%" src="<?php echo $this->baseUrl()?>/img/logo/autosys-logo-hr.png">
                </a>
            </div>
            <nav class="top-nav" role="navigation">
                <ul class="nav navbar-nav pull-left">
                    <li id="toggle-sidebar-li">
                        <a href="#" id="toggle-sidebar"><i class="en-arrow-left2"></i></a>
                    </li>
                    
                    <li class="dropdown">
                        <a href="<?php echo $this->baseUrl('index/mudar-cenario'); ?>">
                            <i class="ec-download"></i>
                            <strong><?php echo strtoupper(Zend_Auth::getInstance()->getIdentity()->organizacao->st_nome_fantasia) ?></strong>
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown">
                            <img class="user-avatar" src="<?php echo $this->baseUrl()?>/img/fotos/usuario/<?php echo App_Identity::getIdUsuario()?>.png"><?php echo App_Identity::get('st_usuario'); ?>
                        </a>
                        <ul class="dropdown-menu right" role="menu">
                            <li><a href="<?php echo $this->baseUrl("usuario/profile/index")?>"><i class="st-user"></i> Profile</a></li>
                            <li><a href="#"><i class="st-settings"></i> Configurações</a></li>
                            <li><a href="<?php echo $this->baseUrl('auth')?>"><i class="im-exit"></i> Sair</a></li>
                        </ul>
                    </li>
                    <!-- <li id="toggle-right-sidebar-li"><a href="#" id="toggle-right-sidebar"><i class="ec-users"></i> <span class="notification">3</span></a></li>-->
                </ul>
            </nav>
        </div>
    </div>
    <!-- Start .header-inner -->
</div>

<!-- Start #sidebar -->

<div id="sidebar">
    <!-- Start .sidebar-inner -->
    <div class="sidebar-inner">
        <!-- Start .sidebar-panel -->
        <div class="sidebar-panel panel-nav-header dark-bg">
            <h4 class="sidebar-panel-title">Expandir Menu</h4>
            <a href="#" id="expand-all-submenus" class="expand-submenus tip" title="Expand all sub menus"><i class="en-plus"></i> </a>
        </div>
        <!-- End .sidebar-panel -->
        <!-- Start #sideNav -->
        <ul id="sideNav" class="nav nav-pills nav-stacked">
            <li class="top-search">
                <form>
                    <input type="text" name="search" placeholder="Pesquisar ...">
                    <button type="submit"><i class="ec-search s20"></i>
                    </button>
                </form>
            </li>

            <li>
                <a href="<?php echo $this->baseUrl("administrativo/painel")?>">Dashboard <i class="fa fa-home"></i></a>
            </li>
            <li>
                <a href="#"> Cadastro <i class="fa fa-edit"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("cliente/cliente/listagem")?>"><i class="en-arrow-right7"></i>Cliente</a></li>
                    <li><a href="<?php echo $this->baseUrl("veiculo/veiculo/listagem")?>"><i class="en-arrow-right7"></i>Veículo</a></li>
                    <li><a href="<?php echo $this->baseUrl("fornecedor/fornecedor/listagem")?>"><i class="en-arrow-right7"></i>Fornecedor</a></li>
                </ul>
            </li>
            
            <li><a href="#"> Produto <i class="fa fa-barcode"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("produto/produto/listagem")?>"><i class="en-arrow-right7"></i> Gerenciar Produtos</a></li>
                    <li><a href="<?php echo $this->baseUrl("produto/marca/listagem")?>"><i class="en-arrow-right7"></i> Marca Produtos</a></li>
                </ul>
            </li>            
            <li>
                <a href="#"> Serviço <i class='fa fa-wrench'></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl('servico/servico/listagem')?>"><i class="en-arrow-right7"></i> Gerenciar Serviços</a></li>                    
                </ul>
            </li>
            <li>
            	<a href="#"> Orçamento <i class="fa fa-keyboard"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Gerenciar Orçamentos</a></li>
                </ul>
            </li>
            <li>
            	<a href="#"> Ordem de Serviço <i class="st-download"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("servico/ordem/listagem")?>"><i class="en-arrow-right7"></i> Gerenciar OS</a></li>
                </ul>
            </li>
            <li>
            	<a href="#"> Vendas <i class="br-cart"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Vendas Balcão</a></li>
                </ul>
            </li>
            <li>
            	<a href="#"> Estoque <i class="fa fa-archive"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Gerenciar Estoque</a></li>
                </ul>
            </li>
            <li><a href="#"> Financeiro <i class="fa fa-dollar"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Contas a Pagar</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Contas a Receber</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Fluxo de Caixa</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Boletos Bancários</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Caixa</a></li>
                </ul>
            </li>
            <li><a href="#"> Tabelas Auxiliares <i class="fa fa-table"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Tipo Pessoa</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Perfil</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Função</a></li>
                </ul>
            </li>
            <li><a href="#"> Relatórios <i class="st-files"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Cadastros</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Produtos</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Vendas</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Estoque</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Ordens de Serviços</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Financeiros</a></li>
                </ul>
            </li>
            <li><a href="#"> Configurações <i class="st-settings"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("organizacao/organizacao/listagem")?>"><i class="en-arrow-right7"></i>Dados da Empresa</a></li>
                    <li><a href="<?php echo $this->baseUrl("funcionario/funcionario/listagem")?>"><i class="en-arrow-right7"></i>Funcionário</a></li>
                    <li><a href="<?php echo $this->baseUrl("usuario/usuario/listagem")?>"><i class="en-arrow-right7"></i> Usuários</a></li>
                    <li><a href="<?php echo $this->baseUrl("")?>"><i class="en-arrow-right7"></i>Cadastro Perfil</a></li>
                </ul>
            </li>
            
        </ul>
    </div>
    <!-- End .sidebar-inner -->
</div>