<div id="header">
    <div class="container-fluid">
        <div class="navbar">
            <div class="navbar-header" style="align:center">
                <a class="navbar-brand" href="<?php echo $this->baseUrl()?>/administrativo/painel">
                    <img width="85%" src="">
                    <strong>AUTOSYS</strong><br/>Sistema de Oficina
                </a>
            </div>
            <nav class="top-nav" role="navigation">
                <ul class="nav navbar-nav pull-left">
                    <li id="toggle-sidebar-li">
                        <a href="#" id="toggle-sidebar"><i class="en-arrow-left2"></i></a>
                    </li>
                    
                    <li class="dropdown">
                        <a href="<?php echo $this->baseUrl('index/mudar-cenario'); ?>">
                            <i class="ec-download"></i>
                            <strong><?php echo strtoupper(Zend_Auth::getInstance()->getIdentity()->organizacao->st_nome_fantasia) ?></strong>
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown">
                            <img class="user-avatar" src="<?php echo $this->baseUrl()?>/img/fotos/usuario/<?php echo App_Identity::getIdUsuario()?>.png"><?php echo App_Identity::get('st_usuario'); ?>
                        </a>
                        <ul class="dropdown-menu right" role="menu">
                            <li><a href="profile.html"><i class="st-user"></i> Profile</a></li>
                            <li><a href="#"><i class="st-settings"></i> Configurações</a></li>
                            <li><a href="<?php echo $this->baseUrl('auth')?>"><i class="im-exit"></i> Sair</a></li>
                        </ul>
                    </li>
                    <!-- <li id="toggle-right-sidebar-li"><a href="#" id="toggle-right-sidebar"><i class="ec-users"></i> <span class="notification">3</span></a></li>-->
                </ul>
            </nav>
        </div>
    </div>
    <!-- Start .header-inner -->
</div>

<!-- Start #sidebar -->

<div id="sidebar">
    <!-- Start .sidebar-inner -->
    <div class="sidebar-inner">
        <!-- Start .sidebar-panel -->
        <div class="sidebar-panel panel-nav-header dark-bg">
            <h4 class="sidebar-panel-title">Expandir Menu</h4>
            <a href="#" id="expand-all-submenus" class="expand-submenus tip" title="Expand all sub menus"><i class="en-plus"></i> </a>
        </div>
        <!-- End .sidebar-panel -->
        <!-- Start #sideNav -->
        <ul id="sideNav" class="nav nav-pills nav-stacked">
            <li class="top-search">
                <form>
                    <input type="text" name="search" placeholder="Pesquisar ...">
                    <button type="submit"><i class="ec-search s20"></i>
                    </button>
                </form>
            </li>

          
            <li>
                <a href="<?php echo $this->baseUrl("administrativo/painel")?>">Dashboard <i class="fa-home"></i></a>
            </li>
            <li>
                <a href="#"> Cadastro <i class="fa-edit"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("cliente/cliente/listagem")?>"><i class="en-arrow-right7"></i>Cliente</a></li>
                    <li><a href="<?php echo $this->baseUrl("veiculo/veiculo/listagem")?>"><i class="en-arrow-right7"></i>Veículo</a></li>
                    <li><a href="<?php echo $this->baseUrl("fornecedor/fornecedor/listagem")?>"><i class="en-arrow-right7"></i>Fornecedor</a></li>
                </ul>
            </li>
            
            <li><a href="#"> Produto <i class="fa-barcode"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("produto/produto/index")?>"><i class="en-arrow-right7"></i> Gerenciar Produtos</a></li>
                </ul>
            </li>            
            <li>
                <?php $classe = 'fa-wrench' ?>
                <a href="#"> Serviço <i class="<?php echo $classe ?>"></i></a>
                <ul class="nav sub">
                    <?php $caminho = 'servico/servico/listagem'?>
                    
                    <li><a href="<?php echo $this->baseUrl($caminho)?>"><i class="en-arrow-right7"></i> Gerenciar Serviços</a></li>                    
                </ul>
            </li>
            <li>
            	<a href="#"> Orçamento <i class="fa-keyboard"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Gerenciar Orçamentos</a></li>
                </ul>
            </li>
            <li>
            	<a href="#"> Ordem de Serviço <i class="st-download"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("servico/ordem/listagem")?>"><i class="en-arrow-right7"></i> Gerenciar OS</a></li>
                </ul>
            </li>
            <li>
            	<a href="#"> Vendas <i class="br-cart"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Vendas Balcão</a></li>
                </ul>
            </li>
            <li>
            	<a href="#"> Estoque <i class="fa-archive"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Gerenciar Estoque</a></li>
                </ul>
            </li>
            <li><a href="#"> Financeiro <i class="fa-dollar"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Contas a Pagar</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Contas a Receber</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Fluxo de Caixa</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Boletos Bancários</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Caixa</a></li>
                </ul>
            </li>
            <li><a href="#"> Tabelas Auxiliares <i class="fa-table"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Tipo Pessoa</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Perfil</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Função</a></li>
                </ul>
            </li>
            <li><a href="#"> Relatórios <i class="st-files"></i></a>
                <ul class="nav sub">
                    <li><a href=""><i class="en-arrow-right7"></i> Cadastros</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Produtos</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Vendas</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Estoque</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Ordens de Serviços</a></li>
                    <li><a href=""><i class="en-arrow-right7"></i> Financeiros</a></li>
                </ul>
            </li>
            <li><a href="#"> Configurações <i class="st-settings"></i></a>
                <ul class="nav sub">
                    <li><a href="<?php echo $this->baseUrl("organizacao/organizacao/listagem")?>"><i class="en-arrow-right7"></i>Dados da Empresa</a></li>
                    <li><a href="<?php echo $this->baseUrl("")?>"><i class="en-arrow-right7"></i>Funcionário</a></li>
                    <li><a href="<?php echo $this->baseUrl("usuario/usuario/listagem")?>"><i class="en-arrow-right7"></i> Usuários</a></li>
                    <li><a href="<?php echo $this->baseUrl("")?>"><i class="en-arrow-right7"></i>Cadastro Perfil</a></li>
                </ul>
            </li>
            
        </ul>
    </div>
    <!-- End .sidebar-inner -->
</div>

<!-- End #sidebar -->

<!-- Start #right-sidebar -->
<div id="right-sidebar" class="hide-sidebar">
    <!-- Start .sidebar-inner -->
    <div class="sidebar-inner">
        <div class="sidebar-panel mt0">
            <div class="sidebar-panel-content fullwidth pt0">
                <div class="chat-user-list">
                    <form class="form-horizontal chat-search" role="form">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search for user...">
                            <button type="submit"><i class="ec-search s16"></i>
                            </button>
                        </div>
                        <!-- End .form-group  -->
                    </form>
                    <ul class="chat-ui bsAccordion">
                        <li>
                            <a href="#">Favorites <span class="notification teal">4</span><i class="en-arrow-down5"></i></a>
                            <ul class="in">
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">Chad Engle
                                        <span class="has-message"><i class="im-pencil"></i></span>
                                    </a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/54.jpg" alt="@alagoon">Anthony Lagoon</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/52.jpg" alt="@koridhandy">Kory Handy</a>
                                    <span class="status"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/50.jpg" alt="@divya">Divia Manyan</a>
                                    <span class="status"><i class="en-dot"></i></span>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Online <span class="notification green">3</span><i class="en-arrow-down5"></i></a>
                            <ul class="in">
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/51.jpg" alt="@kolage">Eric Hofman</a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/55.jpg" alt="@mikebeecham">Mike Beecham</a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/53.jpg" alt="@derekebradley">Darek Bradly</a>
                                    <span class="status online"><i class="en-dot"></i></span>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Offline <span class="notification red">5</span><i class="en-arrow-down5"></i></a>
                            <ul>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/56.jpg" alt="@laurengray">Lauren Grey</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">Chad Engle</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/58.jpg" alt="@frankiefreesbie">Frankie Freesibie</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/57.jpg" alt="@joannefournier">Joane Fornier</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                                <li>
                                    <a href="#" class="chat-name">
                                        <img class="chat-avatar" src="<?php echo $this->baseUrl()?>/assets/img/avatars/59.jpg" alt="@aiiaiiaii">Alia Alien</a>
                                    <span class="status offline"><i class="en-dot"></i></span>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="chat-box">
                    <h5>Chad Engle</h5>
                    <a id="close-user-chat" href="#" class="btn btn-xs btn-primary"><i class="en-arrow-left4"></i></a>
                    <ul class="chat-ui chat-messages">
                        <li class="chat-user">
                            <p class="avatar">
                                <img src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">
                            </p>
                            <p class="chat-name">Chad Engle <span class="chat-time">15 seconds ago</span>
                            </p>
                            <span class="status online"><i class="en-dot"></i></span>
                            <p class="chat-txt">Hello Sugge check out the last order.</p>
                        </li>
                        <li class="chat-me">
                            <p class="avatar">
                                <img src="<?php echo $this->baseUrl()?>/assets/img/avatars/48.jpg" alt="A">
                            </p>
                            <p class="chat-name">Admin <span class="chat-time">10 seconds ago</span>
                            </p>
                            <span class="status online"><i class="en-dot"></i></span>
                            <p class="chat-txt">Ok i will check it out.</p>
                        </li>
                        <li class="chat-user">
                            <p class="avatar">
                                <img src="<?php echo $this->baseUrl()?>/assets/img/avatars/49.jpg" alt="@chadengle">
                            </p>
                            <p class="chat-name">Chad Engle <span class="chat-time">now</span>
                            </p>
                            <span class="status online"><i class="en-dot"></i></span>
                            <p class="chat-txt">Thank you, have a nice day</p>
                        </li>
                    </ul>
                    <div class="chat-write">
                        <form action="#" class="form-horizontal" role="form">
                            <div class="form-group">
                                <textarea name="sendmsg" id="sendMsg" class="form-control elastic" rows="1"></textarea>
                                <a role="button" class="btn" id="attach_photo_btn">
                                    <i class="fa-picture s20"></i>
                                </a>
                                <input type="file" name="attach_photo" id="attach_photo">
                            </div>
                            <!-- End .form-group  -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End .sidebar-inner -->
</div>
<!-- End #right-sidebar -->