<?php $dados = $this->dadospagina;?>

<div id="content">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="im-key"></i><strong>CADASTRO DE SERVIÇOS</strong></h1>
                <ul id="crumb" class="breadcrumb">
                </ul>
                <!-- End .breadcrumb -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/servico/servico/listagem')?>">
								<button class="btn btn-primary" type="button"><i class="fa-eye-open"></i> VISUALIZAR CADASTRADOS</button>
							</a>
                        </div>
                        
                    </div>
                </div>
            </div>
		</div>
		
		<?php if(!empty($this->msg)):?>
			<?php if($this->msg == 2) :?>
				<div class="alert alert-success fade in">
					<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
					<i class="fa-ok alert-icon s24"></i>
					<strong>Registro gravado com sucesso!</strong>
				</div>
			<?php else :?>
				<div class="alert alert-danger fade in">
					<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
					<strong>Ocorreu um erro ao gravar!</strong>
				</div>
			<?php endif;?>
		<?php endif;?>
		
		<form id="formCadastro" class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/servico/servico/index')?>">
			
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain">
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">					
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Nome<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_placa" name="st_placa" required  value="<?php echo $this->dadospagina['st_placa']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Código<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="num_ano" name="num_ano" maxlength="4" pattern="([0-9]{3})" value="<?php echo $this->dadospagina['num_ano']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Valor Unitário<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="st_km" name="st_km" value="<?php echo $this->dadospagina['st_km']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Comissão(%)<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
                                    <input type="text" class="form-control left-icon" id="st_km" name="st_km" value="<?php echo $this->dadospagina['st_km']?>" />
								</div>
							</div>
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Observações:</label>
								<div class="col-lg-11 col-md-11">
									<textarea class="form-control" rows="2" id="ds_observacao" name="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
								</div>
							</div>
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default toggle">
        				<button class="btn btn-success  ml15" type="submit"><i class="fa-ok"></i> Cadastrar</button>
        				<a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/servico/servico/')?>">
        					<button class="btn btn-primary" type="button"><i class="fa-plus-sign"></i> Cadastrar Novo</button>
        				</a>
        			</div>	
				</div>
			</div>
		</form>
	</div>
	<div class="clearfix"></div>
</div>

<!-- Modalsimilar -->
<div class="modal fade" id="modalCliente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Existe(m) esse(s) Registro(s) com o mesmo nome</h4>
            </div>
              <div class="modal-body">
                <div class="row">
					<div id="RegSimilar"></div>       
        		</div>            
            </div>
            <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Continuar Cadastro</button>
          </div>
        </div>
    </div>
</div>


<script type="text/javascript" src="<?php echo $this->baseUrl('/js/veiculo/veiculo.js')?>"> </script>

