<div id="content">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="im-key"></i> <strong>CADASTRO DE SERVIÇOS</strong></h1>
                
                <ul id="crumb" class="breadcrumb">
                </ul>
                <!-- End .breadcrumb -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/servico/servico/listagem')?>">
								<button class="btn btn-primary" type="button"><i class="fa-eye-open"></i> VISUALIZAR CADASTROS</button>
							</a>
                        </div>
                        
                    </div>
                </div>
                <!-- End .option-buttons -->
            </div>
		</div>
		
		<?php if(!empty($this->msg)):?>
			<?php if($this->msg == 2) :?>
				<div class="alert alert-success fade in">
					<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
					<i class="fa-ok alert-icon s24"></i>
					<strong>Registro gravado com sucesso!</strong>
				</div>
			<?php else :?>
				<div class="alert alert-danger fade in">
					<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
					<strong>Ocorreu um erro ao gravar!</strong>
				</div>
			<?php endif;?>
		<?php endif;?>
			
		<form id="formCadastro" class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/servico/servico/index')?>">
			
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain">
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Registro: </label>
								<div class="col-lg-3 col-md-3">
									<input class="form-control" type="text" id="id_servico" name="id_servico" readonly="readonly" value="<?php echo $this->dadospagina['id_servico']?>" />
								</div>
								
								<div class="col-lg-2 col-md-2">
									<label class="checkbox-inline">
										<input type="checkbox" value="1" <?php if($this->dadospagina['id_ativo']==1){ echo 'checked ="checked"';}?> style="position: absolute; opacity: 0;" id="id_ativo" name="id_ativo"  /><b>ATIVO</b>
									</label>
								</div>
								
							</div>
											
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Nome<b style="color: red;"> *</b></label>
								<div class="col-lg-5 col-md-2">
									<input type="text" class="form-control" id="st_nome" name="st_nome" required  value="<?php echo $this->dadospagina['st_nome']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Valor<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="num_valor_venda" name="num_valor_venda" required value="<?php echo $this->dadospagina['num_valor_venda']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Comissão(%)</label>
								<div class="col-lg-2 col-md-2">
                                    <input type="text" class="form-control left-icon" id="st_comissao" name="st_comissao" value="<?php echo $this->dadospagina['st_comissao']?>" />
								</div>
							</div>
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Observações:</label>
								<div class="col-lg-11 col-md-11">
									<textarea class="form-control" rows="2" id="ds_observacao" name="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
								</div>
							</div>
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default toggle">
        				<button class="btn btn-success  ml15" type="submit"><i class="fa-ok"></i> Cadastrar</button>
        				<a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/servico/servico/')?>">
        					<button class="btn btn-primary" type="button"><i class="fa-plus-sign"></i> Cadastrar Novo</button>
        				</a>
        			</div>	
				</div>
			</div>
		</form>
	</div>
	<div class="clearfix"></div>
</div>



<script type="text/javascript" src="<?php echo $this->baseUrl('/js/mascara.js')?>"> </script>

