<div id="content">
	<div class="content-wrapper">		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="fa-wrench"></i> <strong>LISTAGEM DE SERVIÇO</strong></h1>
                <ul id="crumb" class="breadcrumb">
                </ul>
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/servico/servico/')?>">
								<button class="btn btn-primary" type="button"><i class="st-file-add"></i> ADICIONAR SERVIÇO</button>
							</a>
                        </div>
                    </div>
                </div>
            </div>
		</div>
		
		<?php if(!empty($this->rsServico)):?>
		
			<div class="outlet">
    			<form class="form-horizontal group-border hover-stripped" role="form">
					<div class="row">
    					<div class="col-lg-12">
							<div class="panel panel-default plain toggle panelClose panelRefresh">
								<div class="panel-heading">
									<h4 class="panel-title">Relatório</h4>
								</div>
								<div class="panel-body">
									<table id="responsive-datatables" class="table table-bordered table-striped table-hover dt-responsive non-responsive" >
										<thead>
											<tr>
												<th>Registro </th>
												<th>Nome</th>
												<th>Valor</th>
												<th>Observação</th>
												<th>Status</th>
												<th>Ação</th>
											</tr>
										</thead>
										<tbody>
											<?php foreach ($this->rsServico as $rsServico) : ?>
												<tr>
                                                	<td><?php echo str_pad($rsServico['id_servico'], 5, "0", STR_PAD_LEFT); ?></td>
                                                    <td><?php echo $rsServico['st_nome'] ?></td>
                                                    <td><?php echo $rsServico['num_valor_venda'] ?></td>
                                                    <td><?php echo $rsServico['ds_observacao'] ?></td>                                                    
                                                    <td><?php echo $rsServico['id_ativo'] == 1 ? '<strong style="color:green;">'.'ATIVO'.'</strong>':'<strong style="color:red;">'.'INATIVO'.'</strong>';?></td>
                                                    <td style="text-align: center;">
                										<a href="<?php echo $this->baseUrl('/servico/servico/index/id/'.base64_encode($rsServico["st_nome"].'@'.$rsServico['id_servico']))?>"><span class="fa-edit s20" title="Editar Registro"></span></a> | 
                										<?php if($rsServico['id_ativo'] == 1) :?>
                											<a href="<?php echo $this->baseUrl('/servico/servico/inativarregistro/id/'.base64_encode($rsServico["id_ativo"].'@'.$rsServico['id_servico']))?>"><span class="fa-remove s20" title="Inativar Registro"></span></a>
                                                    	<?php else :?>
                                                    		<a href="<?php echo $this->baseUrl('/servico/servico/inativarregistro/id/'.base64_encode($rsServico["id_ativo"].'@'.$rsServico['id_servico']))?>"><span class="im-checkmark2 s20" title="Ativar Registro"></span></a>
                                                    	<?php endif; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
    				</div>
    			</form>
    		</div>
		<?php else :?>
            <div class="alert alert-danger fade in" style="text-align: center;">
                <strong>NÃO EXISTEM SERVIÇOS CADASTRADOS, CLIQUE NO BOTÃO "ADICIONAR SERVIÇO" PARA REALIZAR OS CADASTROS</strong>
            </div>
		<?php endif;?>
	</div>
	<div class="clearfix"></div>
</div>