<div id="content">
	<div class="content-wrapper">		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="im-user"></i> <strong>LISTAGEM DE CLIENTES</strong></h1>
                <ul id="crumb" class="breadcrumb">
                </ul>
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/cliente/cliente/')?>">
								<button class="btn btn-primary" type="button"><i class="st-file-add"></i> ADICIONAR CLIENTE</button>
							</a>
                        </div>
                    </div>
                </div>
            </div>
		</div>
		
		<?php if(!empty($this->rsClientes)):?>
		
			<div class="outlet">
    			<form class="form-horizontal group-border hover-stripped" role="form">
					<div class="row">
    					<div class="col-lg-12">
							<div class="panel panel-default plain toggle panelClose panelRefresh">
								<div class="panel-heading">
									<h4 class="panel-title">Relatório</h4>
								</div>
								<div class="panel-body">
									<table id="responsive-datatables" class="table table-bordered table-striped table-hover dt-responsive non-responsive" >
										<thead>
											<tr>
												<th>Registro</th>
												<th>Nome</th>
												<th>CPF/CNPJ</th>
												<th>Sexo</th>
												<th>E-mail</th>
												<th>Status</th>
												<th>Ação</th>
											</tr>
										</thead>
										<tbody>
											<?php foreach ($this->rsClientes as $rsClientes) : ?>
												<tr>
                                                	<td><?php echo str_pad($rsClientes['id_cliente'], 5, "0", STR_PAD_LEFT); ?></td>
                                                    <td><?php echo $rsClientes['st_nome'] ?></td>
                                                    <td><?php echo $rsClientes['st_cpf'] ?></td>
                                                    <td><?php echo $rsClientes['st_sexo'] == 'M' ? 'Masculino' : 'Feminino' ?></td>
                                                    <td><?php echo $rsClientes['st_email'] ?></td>
                                                    <td><?php echo $rsClientes['id_ativo'] == 1 ? '<strong style="color:green;">'.'ATIVO'.'</strong>':'<strong style="color:red;">'.'INATIVO'.'</strong>';?></td>
                                                    <td style="text-align: center;">
                										<a href="<?php echo $this->baseUrl('/cliente/cliente/index/id/'.base64_encode($rsClientes["dt_nascimento"].'@'.$rsClientes['id_cliente']))?>"><span class="fa-edit s20" title="Editar Registro"></span></a> | 
                										<?php if($rsClientes['id_ativo'] == 1) :?>
                											<a href="<?php echo $this->baseUrl('/cliente/cliente/inativarregistro/id/'.base64_encode($rsClientes["id_ativo"].'@'.$rsClientes['id_cliente']))?>"><span class="fa-remove s20" title="Inativar Registro"></span></a>
                                                    	<?php else :?>
                                                    		<a href="<?php echo $this->baseUrl('/cliente/cliente/inativarregistro/id/'.base64_encode($rsClientes["id_ativo"].'@'.$rsClientes['id_cliente']))?>"><span class="im-checkmark2 s20" title="Ativar Registro"></span></a>
                                                    	<?php endif; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
    				</div>
    			</form>
    		</div>
		<?php else :?>
            <div class="alert alert-danger fade in" style="text-align: center;">
                <strong>NÃO EXISTEM CLIENTES CADASTRADOS, CLIQUE NO BOTÃO "ADICIONAR CLIENTE" PARA REALIZAR OS CADASTROS</strong>
            </div>
		<?php endif;?>
	</div>
	<div class="clearfix"></div>
</div>