<div id="content">
	<div class="content-wrapper">		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="fa fa-barcode"></i> <strong>LISTAGEM DE MARCA DE PRODUTOS</strong></h1>
				<ul id="crumb" class="breadcrumb">
                </ul>
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                    	<div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/produto/marca/')?>">
								<button class="btn btn-primary" type="button"><i class="st-file-add"></i> ADICIONAR MARCA DE PRODUTO</button>
							</a>
                        </div>
					</div>
				</div>
			</div>
		</div>
		<?php if(!empty($this->rsMarcaProduto)):?>
			<div class="outlet">
    			<form class="form-horizontal group-border hover-stripped" role="form">
					<div class="row">
    					<div class="col-lg-12">
							<div class="panel panel-default plain toggle panelClose panelRefresh">
								<div class="panel-body">
									<table id="responsive-datatables" class="table table-bordered table-striped table-hover dt-responsive non-responsive" >
										<thead>
											<tr>
												<th>Registro</th>
												<th>Nome</th>
												<th>Ação</th>
											</tr>
										</thead>
										<tbody>
											<?php foreach ($this->rsMarcaProduto as $rProduto) : ?>
												<tr>
                                                	<td><?php echo str_pad($rProduto['id_marca_produto'], 3, "0", STR_PAD_LEFT); ?></td>
                                                    <td><?php echo $rProduto['st_nome'] ?></td>
                                                    <td style="text-align: center;">
                										<a href="<?php echo $this->baseUrl('/produto/marca/index/id/'.base64_encode($rProduto["id_marca_produto"].'@'.$rProduto['id_marca_produto']))?>"><span class="fa-edit s20" title="Editar Registro"></span></a> | 
                										<a href="<?php echo $this->baseUrl('/produto/marca/inativarregistro/id/'.base64_encode($rProduto["id_marca_produto"].'@'.$rProduto['id_marca_produto']))?>"><span class="fa-remove s20" title="Inativar Registro"></span></a>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
    				</div>
    			</form>
    		</div>
		<?php else :?>
            <div class="alert alert-danger fade in" style="text-align: center;">
                <strong>NÃO EXISTEM MARCAS DE PRODUTOS CADASTRADOS, CLIQUE NO BOTÃO "ADICIONAR MARCA DE PRODUTO" PARA REALIZAR OS CADASTROS</strong>
            </div>
		<?php endif;?>
	</div>
	<div class="clearfix"></div>
</div>