<?php $dados = $this->dadospagina;?>

<div id="content">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="st-download"></i><strong>CADASTRO DE ORDEM DE SERVIÇOS</strong></h1>
                <ul id="crumb" class="breadcrumb">
                </ul>
                <!-- End .breadcrumb -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/servico/ordem/listagem')?>">
								<button class="btn btn-primary" type="button"><i class="fa-eye-open"></i> VISUALIZAR CADASTRADOS</button>
							</a>
                        </div>
                        
                    </div>
                </div>
            </div>
		</div>
		
		<?php if(!empty($this->msg)):?>
			<?php if($this->msg == 2) :?>
				<div class="alert alert-success fade in">
					<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
					<i class="fa-ok alert-icon s24"></i>
					<strong>Registro gravado com sucesso!</strong>
				</div>
			<?php else :?>
				<div class="alert alert-danger fade in">
					<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
					<strong>Ocorreu um erro ao gravar!</strong>
				</div>
			<?php endif;?>
		<?php endif;?>
		
		<form id="formCadastro" class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/servico/ordem/index')?>">
			
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain"><h4>Dados Gerais</h4>
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">					
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Cliente<b style="color: red;"> *</b></label>
								<div class="col-lg-4 col-md-4">
									<select id="id_cliente" class="form-control select2"  name="id_cliente" autofocus="autofocus">
										<option></option>
										<?php foreach ($this->rsCliente as $value):?>
											<option value="<?php echo $value['id_cliente']?>" <?php if($this->dadospagina['id_cliente'] == $value['id_cliente']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Data OS<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="dt_os" name="dt_os" value="<?php echo $this->dadospagina['dt_os']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Previsão Entrega<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="st_km" name="st_km" value="<?php echo $this->dadospagina['st_km']?>" />
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Situação<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_placa" name="st_placa"   value="<?php echo $this->dadospagina['st_placa']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Entrada<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="num_ano" name="num_ano" value="<?php echo $this->dadospagina['num_ano']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Saída<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="st_km" name="st_km" value="<?php echo $this->dadospagina['st_km']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Prestador<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
                                    <select id="id_cliente" class="form-control select2"  name="id_cliente" autofocus="autofocus">
										<option></option>
										<?php foreach ($this->rsFuncionario as $value):?>
											<option value="<?php echo $value['id_funcionario']?>" <?php if($this->dadospagina['id_funcionario'] == $value['id_funcionario']) echo "selected"?>><?php echo strtoupper( $value['st_nome']) ?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain"><h4>Equipamento/Descrição</h4>
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Placa<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_placa" name="st_placa"   value="<?php echo $this->dadospagina['st_placa']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Km<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="num_ano" name="num_ano" value="<?php echo $this->dadospagina['num_ano']?>" />
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Codições<b style="color: red;"> *</b></label>
								<div class="col-lg-5 col-md-5">
									<textarea class="form-control" rows="2" id="ds_observacao" name="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Acessórios<b style="color: red;"> *</b>:</label>
								<div class="col-lg-5 col-md-5">
									<textarea class="form-control" rows="2" id="ds_observacao" name="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Defeito<b style="color: red;"> *</b></label>
								<div class="col-lg-5 col-md-5">
									<textarea class="form-control" rows="2" id="ds_observacao" name="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Solução<b style="color: red;"> *</b>:</label>
								<div class="col-lg-5 col-md-5">
									<textarea class="form-control" rows="2" id="ds_observacao" name="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
								</div>
							</div>
						</div>
					</div>
				</div>
								
				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain"><h4>Produtos</h4>
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<table id="tb_produto" class="table table-bordered table-striped table-hover dt-responsive non-responsive" >
            						<thead>
            							<tr>
            								<th>Produtos</th>
            								<th>Valor Unitário</th>
            								<th>Quantidade</th>
            								<th>SubTotal</th>
            								<th>Ação</th>
            							</tr>
            						</thead>
            					</table>
            					<button class="btn btn-dark" type="button" onclick="addProduto()"><i class="fa-plus-sign"></i> Adicionar Produto</button>
							</div>
						</div>
					</div>
				</div>
				
				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain"><h4>Serviços</h4>
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Serviço<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="st_placa" name="st_placa"   value="<?php echo $this->dadospagina['st_placa']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Quantidade<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="num_ano" name="num_ano" value="<?php echo $this->dadospagina['num_ano']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Valor<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="st_km" name="st_km" value="<?php echo $this->dadospagina['st_km']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">SubTotal<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
                                    <input type="text" class="form-control left-icon" id="st_km" name="st_km" value="<?php echo $this->dadospagina['st_km']?>" />
								</div>
							</div>
							<div>
                				<button class="btn btn-dark" type="button"><i class="fa-plus-sign"></i> Adicionar Serviço</button>
        					</div>
						</div>
					</div>
				</div>
				
				<div class="col-lg-12 col-md-12 col-sm-9 col-xs-12">
					<div class="panel panel-default plain"><h4>Total</h4>
						<div class="panel-heading white-bg"></div>
						<div class="panel-body">
							<div class="form-group">
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Produto<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control" id="vl_total_produto" name="vl_total_produto"   value="<?php echo $this->dadospagina['vl_total_produto']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Serviços<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="vl_total_servico" name="vl_total_servico" value="<?php echo $this->dadospagina['vl_total_servico']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label">Desconto<b style="color: red;"> *</b>:</label>
								<div class="col-lg-2 col-md-2">
									<input type="text" class="form-control left-icon" id="vl_desconto" name="vl_desconto" value="<?php echo $this->dadospagina['vl_desconto']?>" />
								</div>
								<label class="col-lg-1 col-md-1 col-sm-12 control-label ">Valor Total<b style="color: red;"> *</b></label>
								<div class="col-lg-2 col-md-2">
                                    <input type="text" class="form-control left-icon" id="vl_total" name="vl_total" value="<?php echo $this->dadospagina['vl_total']?>" />
								</div>
							</div>							
						</div>
					</div>
				</div>
							
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default toggle">
        				<button class="btn btn-success  ml15" type="submit"><i class="fa-ok"></i> Cadastrar</button>
        				<a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/servico/servico/')?>">
        					<button class="btn btn-primary" type="button"><i class="fa-plus-sign"></i> Cadastrar Novo</button>
        				</a>
        			</div>	
				</div>
			</div>
		</form>
	</div>
	<div class="clearfix"></div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/servico/ordemServico.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/mascara.js')?>"> </script>

